# Makefile for Linux

SHELL = /bin/sh

# System-specific settings

CC =		gcc
CCFLAGS =	-O -g -I/home/sjplimp/tools/mpich/include -DCHECK
LINK =		gcc
LINKFLAGS =	-O -g -L/home/sjplimp/tools/mpich/lib
LIB =		-lmpich

# Link target

gups_vanilla:	gups_vanilla.o
	$(LINK) $(LINKFLAGS) gups_vanilla.o $(LIB) -o gups_vanilla

gups_nonpow2:	gups_nonpow2.o
	$(LINK) $(LINKFLAGS) gups_nonpow2.o $(LIB) -o gups_nonpow2

gups_opt:	gups_opt.o
	$(LINK) $(LINKFLAGS) gups_opt.o $(LIB) -o gups_opt

# Compilation rules

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
