# Makefile for Linux

SHELL = /bin/sh

# System-specific settings

CC =		mpiicc
CCFLAGS =	-O3 -g -DCHECK
LINK =		mpiicc
LINKFLAGS =	-O3 -g
LIB =		

# Link target

all: gups_vanilla gups_nonpow2 gups_opt

gups_vanilla:	gups_vanilla.o
	$(LINK) $(LINKFLAGS) gups_vanilla.o $(LIB) -o gups_vanilla

gups_nonpow2:	gups_nonpow2.o
	$(LINK) $(LINKFLAGS) gups_nonpow2.o $(LIB) -o gups_nonpow2

gups_opt:	gups_opt.o
	$(LINK) $(LINKFLAGS) gups_opt.o $(LIB) -o gups_opt

# Compilation rules

%.o:%.c
	$(CC) $(CCFLAGS) -c $<

clean:
	rm -f gups_vanilla gups_nonpow2 gups_opt *.o
