include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../../custom.mak
ifdef OUTPUT
override OUTPUT = -DOUTPUT
endif

HCLIB_PERF_CC?=icc
CC = $(HCLIB_PERF_CC)


# C compiler
CC_FLAGS = -g -O3 -I$(MATRIX_DIR) $(HCLIB_CXXFLAGS)

# Matrix library path
MATRIX_DIR = ../meschach_lib


leukocyte.cuda: detect_main.cuda.o avilib.o find_ellipse.cuda.o track_ellipse.cuda.o misc_math.o $(MATRIX_DIR)/meschach.a
	$(CC) -g -O3 -I$(MATRIX_DIR) -lm $(MATRIX_DIR)/meschach.a avilib.o find_ellipse.cuda.o track_ellipse.cuda.o misc_math.o detect_main.cuda.o -o leukocyte.cuda -lm $(MATRIX_DIR)/meschach.a -lpthread $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

%.o: %.c
	$(CC) $(OUTPUT) $(CC_FLAGS) $< -c

detect_main.cuda.o: find_ellipse.h track_ellipse.h avilib.h
find_ellipse.cuda.o: avilib.h
track_ellipse.cuda.o: find_ellipse.h track_ellipse.h avilib.h

$(MATRIX_DIR)/meschach.a:
	cd $(MATRIX_DIR); ./configure --with-all; make all; make clean

clean:
	rm -f *.o leukocyte.cuda
