include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak

# C compiler
HCLIB_PERF_CC?=icc
CC = $(HCLIB_PERF_CC)
CC_FLAGS=-g -O2 $(HCLIB_CXXFLAGS)


backprop.cuda: backprop.cuda.o facetrain.cuda.o imagenet.o backprop_kernel.o 
	$(CC) -g -O2 backprop.cuda.o facetrain.cuda.o \
		imagenet.o backprop_kernel.o $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS) -o backprop.cuda -lm

%.o: %.[ch]
	$(CC) $(CC_FLAGS) $< -c

facetrain.cuda.o: facetrain.cuda.c backprop.h
	$(CC) $(CC_FLAGS) facetrain.cuda.c -c
	
backprop.cuda.o: backprop.c backprop.h
	$(CC) $(CC_FLAGS) backprop.cuda.c -c

backprop_kernel.o: backprop_kernel.c backprop.h
	$(CC) $(CC_FLAGS) backprop_kernel.c -c

imagenet.o: imagenet.c backprop.h
	$(CC) $(CC_FLAGS) imagenet.c -c


clean:
	rm -f *.o *~ backprop backprop_cuda.linkinfo
