#!/bin/bash
#PBS -A csc205
#PBS -N max
#PBS -j oe
#PBS -m abe
#PBS -q debug
#PBS -l walltime=00:05:00
#PBS -l nodes=512
#PBS -l gres=atlas1%atlas2
#PBS -V

# export GASNET_MAX_SEGSIZE='4294967296'
# cd $PBS_O_WORKDIR
cd /ccs/proj/csc205/max/hclib/test/performance-regression/cpu-only/isx

export LD_LIBRARY_PATH=/opt/gcc/4.9.0/snos/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$PROJ_DIR/hclib/modules/openshmem/lib:$LD_LIBRARY_PATH
export HCLIB_LOCALITY_FILE=$PROJ_DIR/hclib/locality_graphs/titan.no_gpu.json
export GASNET_BACKTRACE=1
export LD_PRELOAD=/lustre/atlas/sw/tbb/43/sles11.3_gnu4.8.2/source/build/linux_intel64_gcc_cc4.8.2_libc2.11.3_kernel3.0.101_release/libtbbmalloc_proxy.so.2
ulimit -c unlimited

NODES=$PBS_NUM_NODES

for REPEAT in {1..5}; do
    # export SMA_SYMMETRIC_SIZE=402653184
    # export SHMEM_SYMMETRIC_HEAP_SIZE=$SMA_SYMMETRIC_SIZE
    # export GASNET_PHYSMEM_MAX=16G
    # aprun -n $(($NODES * 16)) -N 16 -S 8 -d 1 ./bin/isx.weak 33554432 /tmp/output_weak

    export SMA_SYMMETRIC_SIZE=1207959552
    export SHMEM_SYMMETRIC_HEAP_SIZE=$SMA_SYMMETRIC_SIZE
    export GASNET_PHYSMEM_MAX=16G
    export OMP_NUM_THREADS=8
    export HCLIB_WORKERS=8
    aprun -n $(($NODES * 2)) -d 8 -N 2 -S 1 ./bin/isx.hclib.weak 268435456 /tmp/output_weak

    # export SMA_SYMMETRIC_SIZE=1207959552
    # export SHMEM_SYMMETRIC_HEAP_SIZE=$SMA_SYMMETRIC_SIZE
    # export GASNET_PHYSMEM_MAX=16G
    # export OMP_NUM_THREADS=8
    # export HCLIB_WORKERS=8
    # aprun -n $(($NODES * 2)) -d 8 -N 2 -S 1 ./bin/isx.omp.weak 268435456 /tmp/output_weak
done

# export OMP_NUM_THREADS=1
# export HCLIB_WORKERS=1
# aprun -ss -n $(($NODES * 16)) -d 1 -N 16 -S 8 ./bin/isx.hclib.weak 33554432 /tmp/output_weak
# 

# export ISX_PE_CHUNKS=1

# export OMP_NUM_THREADS=1
# export HCLIB_WORKERS=1
# aprun -ss -n $(($NODES * 16)) -d 1 -N 16 -S 8 ./bin/isx.omp.weak 33554432 /tmp/output_weak


# export OMP_NUM_THREADS=8
# export HCLIB_WORKERS=8
# aprun -cc 0,1,2,3,4,5,6,7:8,9,10,11,12,13,14,15 -n $(($NODES * 2)) -d 8 -N 2 -S 1 ./bin/isx.omp.weak 33554432 /tmp/output_weak

# export OMP_NUM_THREADS=8
# aprun -n 512 -ss -S 8 -d 1 ./bin/isx.omp.weak 33554432 /tmp/output_weak
# export OMP_NUM_THREADS=1
# aprun -n 64 -cc 0,1,2,3,4,5,6,7:8,9,10,11,12,13,14,15 -ss -S 1 -d 8 ./bin/isx.omp.weak 33554432 /tmp/output_weak
