#!/bin/bash
#PBS -A csc205
#PBS -N max
#PBS -j oe
#PBS -q debug
#PBS -l walltime=00:20:00
#PBS -l nodes=8
#PBS -l gres=atlas1%atlas2
#PBS -V

# export GASNET_MAX_SEGSIZE='512MB'
# cd $PBS_O_WORKDIR
cd /ccs/proj/csc205/max/hclib/test/performance-regression/cpu-only/isx

export LD_LIBRARY_PATH=$PROJ_DIR/hclib/modules/openshmem/lib:$LD_LIBRARY_PATH
export HCLIB_LOCALITY_FILE=$PROJ_DIR/hclib/locality_graphs/titan.no_gpu.json
export GASNET_BACKTRACE=1
export SMA_SYMMETRIC_SIZE=2147483648
export GASNET_PHYSMEM_MAX=2G
export LD_PRELOAD=/lustre/atlas/sw/tbb/43/sles11.3_gnu4.8.2/source/build/linux_intel64_gcc_cc4.8.2_libc2.11.3_kernel3.0.101_release/libtbbmalloc_proxy.so.2
ulimit -c unlimited

NODES=$PBS_NUM_NODES

aprun -ss -n $(($NODES * 16)) -d 1 -N 16 -S 8 ./bin/isx.weak 33554432 /tmp/output_weak

export OMP_NUM_THREADS=1
export HCLIB_WORKERS=1
aprun -ss -n $(($NODES * 16)) -d 1 -N 16 -S 8 ./bin/isx.hclib.weak 33554432 /tmp/output_weak

# export OMP_NUM_THREADS=8
# export HCLIB_WORKERS=8
# aprun -n $(($NODES * 2)) -d 8 -N 2 -S 1 ./bin/isx.hclib.weak 268435456 /tmp/output_weak
