PROJECT_CXXFLAGS=-O3 -std=c++11 -I$(HCPP_ROOT)/include -I$(LIBXML2_INCLUDE)
PROJECT_LDFLAGS=-O3 -L$(LIBXML2_LIBS) -L$(HCPP_ROOT)/lib
PROJECT_LDLIBS=-lhcpp -lxml2
ifdef TBB_MALLOC
  PROJECT_LDFLAGS+=-L$(TBB_MALLOC)
  PROJECT_LDLIBS+=-ltbbmalloc_proxy
endif
