include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak

# C compiler
HCLIB_PERF_CXX?=icpc
CC_FLAGS = -g -fopenmp -O2 $(HCLIB_CXXFLAGS)

all: bfs.ref

bfs.ref: bfs.ref.cpp 
	$(HCLIB_PERF_CXX) $(CC_FLAGS) bfs.ref.cpp $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS) -o bfs.ref

clean:
	rm -f bfs.ref result.txt
