include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak

HCLIB_PERF_CXX?=icpc
CC=$(HCLIB_PERF_CXX)

CC_FLAGS=-g -O2 $(HCLIB_CXXFLAGS)

all: bfs.cuda

bfs.cuda: bfs.cuda.o
	$(CC) -g -O2 -o bfs.cuda bfs.cuda.o $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

bfs.cuda.o: bfs.cuda.cpp
	$(CC) -c $(CC_FLAGS) bfs.cuda.cpp -o bfs.cuda.o

clean:
	rm -f bfs.cuda result.txt *.o
