include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
# C compiler
HCLIB_PERF_CXX?=icpc
CC_FLAGS = -g -fopenmp -O2

all: hotspot.ref

hotspot.ref: hotspot_openmp.ref.cpp Makefile.ref
	$(HCLIB_PERF_CXX) $(CC_FLAGS) hotspot_openmp.ref.cpp -o hotspot.ref $(HCLIB_CXXFLAGS) $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

clean:
	rm -f hotspot.ref
