include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak
HCLIB_PERF_CXX?=icpc
LOCAL_CC = $(HCLIB_PERF_CXX) -g -O3 -Wall
CFLAGS = -lm -Wall $(HCLIB_CXXFLAGS)


all : nn.ref

clean :
	rm -rf *.o nn.ref hurricane_gen

nn.ref : nn_openmp.ref.c
	$(HCLIB_PERF_CXX) -o $@ $< $(LDFLAGS) $(CFLAGS) $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

hurricane_gen : hurricane_gen.c
	$(LOCAL_CC) -o $@ $< -lm

