include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak

HCLIB_PERF_CXX?=icpc
CC = $(HCLIB_PERF_CXX)
LOCAL_CC = $(CC) -g -O3
CFLAGS = -lm $(HCLIB_CXXFLAGS)


all : nn.cuda

clean :
	rm -rf *.o nn.cuda hurricane_gen

nn.cuda : nn_openmp.cuda.c
	$(CC) -c -o nn_openmp.cuda.o $< $(LDFLAGS) $(CFLAGS)
	$(CC) -o $@ nn_openmp.cuda.o $(LDFLAGS) -lm $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

hurricane_gen : hurricane_gen.c
	$(LOCAL_CC) -o $@ $< -lm

