include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak
# C compiler
HCLIB_PERF_CXX?=icpc
CC_FLAGS = -g -O2 $(HCLIB_CXXFLAGS)

srad.ref:
	$(HCLIB_PERF_CXX) $(CC_FLAGS) srad.ref.cpp -o srad.ref $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

clean:
	rm -f srad.ref
