include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak
# C compiler
HCLIB_PERF_CXX?=icpc
CC_FLAGS = -g -fopenmp -O2 $(HCLIB_CXXFLAGS)

srad.balance:
	$(HCLIB_PERF_CXX) $(CC_FLAGS) srad.balance.cpp -o srad.balance $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

clean:
	rm -f srad.balance
