namespace hcpp { 
  void asyncPhased(std::function<void()> &&lambda); 
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, PHASER_t* ph13, PHASER_m m13, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, PHASER_t* ph13, PHASER_m m13, PHASER_t* ph14, PHASER_m m14, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, PHASER_t* ph13, PHASER_m m13, PHASER_t* ph14, PHASER_m m14, PHASER_t* ph15, PHASER_m m15, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, PHASER_t* ph13, PHASER_m m13, PHASER_t* ph14, PHASER_m m14, PHASER_t* ph15, PHASER_m m15, PHASER_t* ph16, PHASER_m m16, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, PHASER_t* ph13, PHASER_m m13, PHASER_t* ph14, PHASER_m m14, PHASER_t* ph15, PHASER_m m15, PHASER_t* ph16, PHASER_m m16, PHASER_t* ph17, PHASER_m m17, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, PHASER_t* ph13, PHASER_m m13, PHASER_t* ph14, PHASER_m m14, PHASER_t* ph15, PHASER_m m15, PHASER_t* ph16, PHASER_m m16, PHASER_t* ph17, PHASER_m m17, PHASER_t* ph18, PHASER_m m18, std::function<void()> &&lambda);
  void asyncPhased(PHASER_t* ph0, PHASER_m m0, PHASER_t* ph1, PHASER_m m1, PHASER_t* ph2, PHASER_m m2, PHASER_t* ph3, PHASER_m m3, PHASER_t* ph4, PHASER_m m4, PHASER_t* ph5, PHASER_m m5, PHASER_t* ph6, PHASER_m m6, PHASER_t* ph7, PHASER_m m7, PHASER_t* ph8, PHASER_m m8, PHASER_t* ph9, PHASER_m m9, PHASER_t* ph10, PHASER_m m10, PHASER_t* ph11, PHASER_m m11, PHASER_t* ph12, PHASER_m m12, PHASER_t* ph13, PHASER_m m13, PHASER_t* ph14, PHASER_m m14, PHASER_t* ph15, PHASER_m m15, PHASER_t* ph16, PHASER_m m16, PHASER_t* ph17, PHASER_m m17, PHASER_t* ph18, PHASER_m m18, PHASER_t* ph19, PHASER_m m19, std::function<void()> &&lambda);
}
