include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
# C compiler
HCLIB_PERF_CXX?=icpc
CC_FLAGS = -g -O3 -fopenmp $(HCLIB_CXXFLAGS)

all: needle.ref

needle.ref: needle.ref.cpp
	$(HCLIB_PERF_CXX) $(CC_FLAGS) needle.ref.cpp -o needle.ref  $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

clean:
	rm -f needle.ref
