include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak

ifdef OUTPUT
override OUTPUT = -DOUTPUT
endif

HCLIB_PERF_CC?=icc
CC = $(HCLIB_PERF_CC)

# link objects(binaries) together
heartwall.cuda: main.cuda.o kernel.cuda.o ./AVI/avilib.o ./AVI/avimod.o
	$(CC) main.cuda.o kernel.cuda.o ./AVI/avilib.o ./AVI/avimod.o -lm -o heartwall.cuda $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

# compile main function file into object (binary)
main.cuda.o: main.cuda.c
	$(CC) $(OUTPUT) main.cuda.c -I./AVI -c -O3 $(HCLIB_CXXFLAGS)

kernel.cuda.o: kernel.cuda.c
	$(CC) $(OUTPUT) kernel.cuda.c -I./AVI -c -O3 $(HCLIB_CXXFLAGS)

./AVI/avilib.o ./AVI/avimod.o:
	cd AVI; make;

# delete all object files
clean:
	rm -f *.o AVI/*.o heartwall.cuda
