include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
LOCAL_CC = gcc -g -O3 -Wall
CC = gcc
CFLAGS = -lm -fopenmp -Wall $(HCLIB_CXXFLAGS)


all : nn.ref

clean :
	rm -rf *.o nn.ref hurricane_gen

nn.ref : nn_openmp.ref.c
	g++ -o $@ $< $(LDFLAGS) $(CFLAGS) $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

hurricane_gen : hurricane_gen.c
	$(LOCAL_CC) -o $@ $< -lm

