include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak
#makefile

HCLIB_PERF_CXX?=icpc
CC = $(HCLIB_PERF_CXX)

particle_filter.cuda: ex_particle_OPENMP_seq.cuda.c
	$(CC) -c -O3 ex_particle_OPENMP_seq.cuda.c -o particle_filter.cuda.o $(HCLIB_CXXFLAGS)
	$(CC) -O3 particle_filter.cuda.o -o particle_filter.cuda -lm  $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)


clean:
	rm -f particle_filter.cuda *.o
