include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak
#makefile
HCLIB_PERF_CXX?=icpc

particle_filter.ref: ex_particle_OPENMP_seq.ref.c
	$(HCLIB_PERF_CXX) -O3 -ffast-math ex_particle_OPENMP_seq.ref.c -o particle_filter.ref -lm  $(HCLIB_CXXFLAGS) $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)


clean:
	rm -f particle_filter.ref
