include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak
# C compiler
HCLIB_PERF_CC?=icc
CC = $(HCLIB_PERF_CC)
CC_FLAGS = -g -fopenmp -O0

kmeans.ref: cluster.o getopt.o kmeans.ref.o kmeans_clustering.ref.o 
	$(HCLIB_PERF_CC) $(CC_FLAGS) cluster.o getopt.o kmeans.ref.o kmeans_clustering.ref.o  -o kmeans.ref $(HCLIB_CXXFLAGS) $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

%.o: %.[ch]
	$(CC) $(CC_FLAGS) $< -c $(HCLIB_CXXFLAGS)

cluster.o: cluster.c 
	$(CC) $(CC_FLAGS) cluster.c -c $(HCLIB_CXXFLAGS)
	
getopt.o: getopt.c 
	$(CC) $(CC_FLAGS) getopt.c -c $(HCLIB_CXXFLAGS)
	
kmeans.ref.o: kmeans.ref.c 
	$(CC) $(CC_FLAGS) kmeans.ref.c -c $(HCLIB_CXXFLAGS)

kmeans_clustering.ref.o: kmeans_clustering.ref.c kmeans.h
	$(CC) $(CC_FLAGS) kmeans_clustering.ref.c -c $(HCLIB_CXXFLAGS)

clean:
	rm -f *.o *~ kmeans.ref 
