include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.pre.mak
include $(HCLIB_ROOT)/include/hclib.mak
include $(HCLIB_ROOT)/../modules/system/inc/hclib_system.post.mak
include ../../custom.mak
# C compiler
HCLIB_PERF_CC?=icc
CC = $(HCLIB_PERF_CC)
CC_FLAGS = -g -O0

kmeans.cuda: cluster.o getopt.o kmeans.cuda.o kmeans_clustering.cuda.o 
	$(CC) $(CC_FLAGS) cluster.o getopt.o kmeans.cuda.o kmeans_clustering.cuda.o  -o kmeans.cuda $(HCLIB_LDFLAGS) $(HCLIB_LDLIBS)

%.o: %.[ch]
	$(CC) $(CC_FLAGS) $< -c $(HCLIB_CXXFLAGS)

cluster.o: cluster.c 
	$(CC) $(CC_FLAGS) cluster.c -c $(HCLIB_CXXFLAGS)
	
getopt.o: getopt.c 
	$(CC) $(CC_FLAGS) getopt.c -c $(HCLIB_CXXFLAGS)
	
kmeans.cuda.o: kmeans.cuda.c 
	$(CC) $(CC_FLAGS) kmeans.cuda.c -c $(HCLIB_CXXFLAGS)

kmeans_clustering.cuda.o: kmeans_clustering.cuda.c kmeans.h
	$(CC) $(CC_FLAGS) kmeans_clustering.cuda.c -c $(HCLIB_CXXFLAGS)

clean:
	rm -f *.o *~ kmeans.cuda 
